# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CzZ3BgR6oIAPQGoQ0zodUzbyH8ZPdBtX
"""

from fastapi import FastAPI, UploadFile, File, Form
from fastapi.middleware.cors import CORSMiddleware
import tensorflow as tf
import numpy as np
import cv2
import firebase_admin
from firebase_admin import credentials, firestore
import os
import json

app = FastAPI()
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # permite todos los orígenes
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Cargar modelo
model = tf.keras.models.load_model("pothole_model.h5")

# Firebase config
firebase_key = json.loads(os.environ["FIREBASE_KEY"])
cred = credentials.Certificate(firebase_key)
firebase_admin.initialize_app(cred)
db = firestore.client()

IMG_SIZE = 128

def preprocess(image_bytes):
    npimg = np.frombuffer(image_bytes, np.uint8)
    img = cv2.imdecode(npimg, cv2.IMREAD_COLOR)
    img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
    img = img / 255.0
    img = np.expand_dims(img, axis=0)
    return img

@app.post("/predict/")
async def predict(file: UploadFile = File(...), lat: float = Form(...), lon: float = Form(...)):
    contents = await file.read()
    img = preprocess(contents)

    prediction = model.predict(img)[0][0]

    print("Predicción:", prediction)
    print("Lat:", lat, "Lon:", lon)

    if prediction > 0.5:
        db.collection("potholes").add({
            "latitude": lat,
            "longitude": lon,
            "confidence": float(prediction)
        })
    return {"prediction": float(prediction)}

@app.get("/potholes")
def get_potholes():

    docs = db.collection("potholes").stream()

    potholes = []

    for doc in docs:
        potholes.append(doc.to_dict())

    return potholes

